### ISSUE TITLE
ppigremlin working with only the provided sample datasets file, unable to run with any new input file.

### ISSUE THREAD

**Issue by Priya-bic** [ppigremlin/ppiGremlin#1]
After successful installation of the program, the program runs (reads the pdbidfile) with the developer's provided bcl.txt/soybean.txt sample file but gets struck at downloading the pdbs.
Moreover, when i tried with a new input pdbidfile created with just first 50 lines of the provided bcl.txt, the program is unable to read the input pdbidfile and writes the error messgae as following:

INFO:root:---Read PDB ids file---
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    pdbids, chains = cm.read_pdbid_file(pdbids_file)
  File "/home/priya/Softwares/ppiGremlin-master/common.py", line 133, in read_pdbid_file
    chains = list(filter(lambda x: x[0][0] != "#",chains))
  File "/home/priya/Softwares/ppiGremlin-master/common.py", line 133, in <lambda>
    chains = list(filter(lambda x: x[0][0] != "#",chains))
IndexError: string index out of range

I also tried running the program with a renamed copy of the provided bcl.txt file with deleting one of the line from the bcl.txt dataset, then also , the program throws the same error.

Could someone please suggest what is the mistake i am making ? or if the program requires the pdb ids as some sorts of pairs which is getting disturbed on deleting just one line from the sample bcl.txt file?
Also, does this program require any minimum number of pdb ids in the input set?

Please reply soon. Thanks in advance.

**Comment by heliohsilva** [comment]
> After successful installation of the program, the program runs (reads the pdbidfile) with the developer's provided bcl.txt/soybean.txt sample file but gets struck at downloading the pdbs. Moreover, when i tried with a new input pdbidfile created with just first 50 lines of the provided bcl.txt, the program is unable to read the input pdbidfile and writes the error messgae as following:
> 
> INFO:root:---Read PDB ids file--- Traceback (most recent call last): File "main.py", line 36, in pdbids, chains = cm.read_pdbid_file(pdbids_file) File "/home/priya/Softwares/ppiGremlin-master/common.py", line 133, in read_pdbid_file chains = list(filter(lambda x: x[0][0] != "#",chains)) File "/home/priya/Softwares/ppiGremlin-master/common.py", line 133, in chains = list(filter(lambda x: x[0][0] != "#",chains)) IndexError: string index out of range
> 
> I also tried running the program with a renamed copy of the provided bcl.txt file with deleting one of the line from the bcl.txt dataset, then also , the program throws the same error.
> 
> Could someone please suggest what is the mistake i am making ? or if the program requires the pdb ids as some sorts of pairs which is getting disturbed on deleting just one line from the sample bcl.txt file? Also, does this program require any minimum number of pdb ids in the input set?
> 
> Please reply soon. Thanks in advance.

Hi!
I had the same issue in some of many times that I runned the code. For me, this was fixed when I added 2 more checks in this function. the condition if the line is empty and the condition if the first element of the line is empty:

chains = list(
            filter(lambda x: len(x) > 0 and len(x[0]) > 0 and x[0][0] != "#", chains)
        )
        
O resultado do codigo da funçao em questao é este acima

**Comment by heliohsilva** [comment]
> After successful installation of the program, the program runs (reads the pdbidfile) with the developer's provided bcl.txt/soybean.txt sample file but gets struck at downloading the pdbs. Moreover, when i tried with a new input pdbidfile created with just first 50 lines of the provided bcl.txt, the program is unable to read the input pdbidfile and writes the error messgae as following:
> 
> INFO:root:---Read PDB ids file--- Traceback (most recent call last): File "main.py", line 36, in pdbids, chains = cm.read_pdbid_file(pdbids_file) File "/home/priya/Softwares/ppiGremlin-master/common.py", line 133, in read_pdbid_file chains = list(filter(lambda x: x[0][0] != "#",chains)) File "/home/priya/Softwares/ppiGremlin-master/common.py", line 133, in chains = list(filter(lambda x: x[0][0] != "#",chains)) IndexError: string index out of range
> 
> I also tried running the program with a renamed copy of the provided bcl.txt file with deleting one of the line from the bcl.txt dataset, then also , the program throws the same error.
> 
> Could someone please suggest what is the mistake i am making ? or if the program requires the pdb ids as some sorts of pairs which is getting disturbed on deleting just one line from the sample bcl.txt file? Also, does this program require any minimum number of pdb ids in the input set?
> 
> Please reply soon. Thanks in advance.

Hi @Priya-bic!!
I had the same issue many times when I ran the code. For me, this was fixed when I added 2 more checks in this function. the condition if the line is empty and the condition if the first element of the line is empty:

chains = list(
filter(lambda x: len(x) > 0 and len(x[0]) > 0 and x[0][0] != "#", chains)
)

O resultado do codigo da funçao em questao é este acima

**Comment by heliohsilva** [comment]
> After successful installation of the program, the program runs (reads the pdbidfile) with the developer's provided bcl.txt/soybean.txt sample file but gets struck at downloading the pdbs. Moreover, when i tried with a new input pdbidfile created with just first 50 lines of the provided bcl.txt, the program is unable to read the input pdbidfile and writes the error messgae as following:
> 
> INFO:root:---Read PDB ids file--- Traceback (most recent call last): File "main.py", line 36, in pdbids, chains = cm.read_pdbid_file(pdbids_file) File "/home/priya/Softwares/ppiGremlin-master/common.py", line 133, in read_pdbid_file chains = list(filter(lambda x: x[0][0] != "#",chains)) File "/home/priya/Softwares/ppiGremlin-master/common.py", line 133, in chains = list(filter(lambda x: x[0][0] != "#",chains)) IndexError: string index out of range
> 
> I also tried running the program with a renamed copy of the provided bcl.txt file with deleting one of the line from the bcl.txt dataset, then also , the program throws the same error.
> 
> Could someone please suggest what is the mistake i am making ? or if the program requires the pdb ids as some sorts of pairs which is getting disturbed on deleting just one line from the sample bcl.txt file? Also, does this program require any minimum number of pdb ids in the input set?
> 
> Please reply soon. Thanks in advance.

Hi @Priya-bic!!
I had the same issue many times when I ran the code. For me, this was fixed when I added 2 more checks in this function. the condition if the line is empty and the condition if the first element of the line is empty:

chains = list(
filter(lambda x: len(x) > 0 and len(x[0]) > 0 and x[0][0] != "#", chains)
)

The result after changes was the above
